### ISSUE TITLE
`NightAndDay` breaks `.previewLayout(.sizeThatsFits)`

### ISSUE THREAD

**Issue by pteasima** [finestructure/PreviewProviderTools#6]
Thanks for the awesome work!

Using `NightAndDay` seems to break `.previewLayout(.sizeThatsFits)`, in different ways, depending on whether I use `.previewLayout` inside or outside of `NightAndDay`.

Is there a different way to achieve `.sizeThatFits` with Gala?

Im opening this issue without much research with hope that you'll instantly know whats going on. If not, Im happy to investigate more and PR if I can find a solution.

**Comment by finestructure** [comment]
Hey @pteasima !

Glad you're finding Gala useful :) Have you tried it with Gala's `Layouts([...]) { }` wrapper? It might help with nesting. I'll need to check but I added a ZStack recently (5c298590ab24f863da2799d64ea38c866e1d07d3) and that might have messed things up.

**Comment by pteasima** [comment]
Same results with `Layouts([.sizeThatFits])` unfortunatelly. When you combine it with `NightAndDay`, you either get an iPhone-sized rectangle or an actual iPhone with a slightly cut-off content inside.

I have to run now but let me know if you're on it or I should have a closer look. Thanks.

**Comment by finestructure** [comment]
Aw, too bad - thanks for checking. I don't think I'll have a chance to look into this anytime soon so if you can figure that one out that'd be great!

**Comment by pteasima** [comment]
It was indeed the ZStack, thanks for the pointer ;)

PR: #7

**Comment by finestructure** [comment]
Ah, fantastic - thanks for fixing this!
